// hui-react/src/components/ListboxPlain.tsx
import { FC, Fragment } from "react";
import { Listbox } from "@headlessui/react";

type ListItem = {
  id: string;
  text: string;
};
type Props = {
  /** 選択肢 */
  items: ListItem[];
  /** 選択項目 */
  value: string | null;
  /** 未選択時に表示するテキスト */
  prompt?: string;
  /** 選択変更時のコールバック */
  onChange?: (value: string | null) => void;
};

const findItem = (items: ListItem[], value: string | null) =>
  items.find((item) => item.id === value);

/**
 * Headless UIのListBoxを利用したオリジナルのリストコンポーネント。
 * スタイルは未適用なのでボタンやリストはブラウザのデフォルトで表示されます。
 * スタイルを適用した例はListboxStyled.tsxを参照してください。
 */
export const ListboxPlain: FC<Props> = ({
  items,
  value,
  prompt = "unselected",
  onChange,
}) => {
  const selectedItem = value ? findItem(items, value) : null;
  const select = (item: ListItem) => onChange?.(item.id);

  return (
    <Listbox value={selectedItem} onChange={select}>
      <Listbox.Button>{selectedItem?.text ?? prompt}</Listbox.Button>
      <Listbox.Options>
        {items.map((item) => (
          <Listbox.Option key={item.id} value={item} as={Fragment}>
            {({ active, selected }) => (
              <li>
                {active && "👉"}
                {selected && "✅"}
                {item.text}
              </li>
            )}
          </Listbox.Option>
        ))}
      </Listbox.Options>
    </Listbox>
  );
};

// hui-vue/src/components/ListboxPlain.vue
<script lang="ts" setup>
// Headless UIのListBoxを利用したオリジナルのリストコンポーネント。
// スタイルは未適用なのでボタンやリストはブラウザのデフォルトで表示されます。
// スタイルを適用した例はListboxStyled.vueを参照してください。

import { computed } from "vue";
import {
  Listbox,
  ListboxButton,
  ListboxOptions,
  ListboxOption,
} from "@headlessui/vue";

type ListItem = {
  id: string;
  text: string;
};

const props = withDefaults(
  defineProps<{
    /** 選択肢 */
    items: ListItem[];
    /** 選択項目 */
    value: string | null;
    /** 未選択時に表示するテキスト */
    prompt?: string;
  }>(),
  {
    prompt: "unselected",
  }
);

const emit = defineEmits<{
  /** 選択肢が変更されたときに発火するイベント */
  (e: "update:value", v: string | null): void;
}>();

/**
 * 選択アイテムを保持するref。
 * ここでは親コンポーネントのprops&emitと連動させるため、computedを使用しています。
 */
const selectedItem = computed<ListItem | null>({
  get() {
    // propsのitemsからvalueに一致するitemを返す
    return props.items.find((item) => item.id === props.value) ?? null;
  },
  set(item) {
    // 選択項目のidをemit
    emit("update:value", item?.id ?? null);
  },
});
</script>

<template>
  <Listbox v-model="selectedItem">
    <ListboxButton>{{ selectedItem?.text ?? prompt }}</ListboxButton>
    <ListboxOptions>
      <ListboxOption
        v-for="item in items"
        :key="item.id"
        :value="item"
        as="template"
        v-slot="{ active, selected }"
      >
        <li>
          <span v-show="active">👉</span>
          <span v-show="selected">✅</span>
          {{ item.text }}
        </li>
      </ListboxOption>
    </ListboxOptions>
  </Listbox>
</template>
